import os

JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY') 
SECRET_KEY = os.getenv('SECRET_KEY') 

PROPAGATE_EXCEPTIONS = True

# Database config

MYSQL_DB_USER = os.getenv('MYSQL_DB_USER')
MYSQL_DB_PASSWD = os.getenv('MYSQL_DB_PASSWD')
MYSQL_DB_IP = os.getenv('MYSQL_DB_IP')
MYSQL_DB_NAME = os.getenv('MYSQL_DB_NAME')

SQLALCHEMY_DATABASE_URI = f'mysql+mysqldb://{MYSQL_DB_USER}:{MYSQL_DB_PASSWD}@{MYSQL_DB_IP}/{MYSQL_DB_NAME}?charset=utf8mb4'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SHOW_SQLALCHEMY_LOG_MESSAGES = True

ERROR_404_HELP = False

